### ISSUE TITLE
Wallet is not resizable

### ISSUE THREAD

**Issue by omdespers** [CryptoCoderz/Espers#17]
I have a UDH Laptop where the wallet appears very small and some lines are not visible. Usually, with qt wallets it is no problem because I can resize them. But espers wallet is not resizable. Please could you fix it , I want to buy espers, but I can´t act with that wallet because I don´t see anything.

**Comment by CryptoCoderz** [comment]
Hello omdespers,

Thank you very much for getting in touch with us and I do apologize about the lengthy wait for a response.

That being said it wasn't known to be have a scaling issue within the wallet as it was purposefully locked at its current size to keep the layout clean and organized in a specific manner. 
What we can do though is release a  large scale UI version so that you and others in your situation won't have to settle with tiny scaled graphics.

Once the whitepapers is finished and released this month (January) we will make the changes to the UI

**Comment by CryptoCoderz** [comment]
Finally closing this issue, the wallet is intentionally not resizable.
