### ISSUE TITLE
Mining is not working

### ISSUE THREAD

**Issue by tatdig** [CryptoCoderz/Espers#47]
"Desired normal spacing: 300: 
Desired maximum spacing: 450: 
Terminal-Velocity 1st multiplier set to: 2.000000: 
Terminal-Velocity 2nd multiplier set to: 1.250000: 
Terminal-Velocity 3rd multiplier set to: 1.000000: 
Terminal-Velocity 4th multiplier set to: 0.750000: 
Terminal-Velocity 5th multiplier set to: 1.000000: 
Terminal-Velocity averaged a final multiplier of: 1.200000: 
Prior Terminal-Velocity: 419512301
New Terminal-Velocity:  419498650
CheckWork() : new proof-of-work block found  
  proof hash: 000000001e00ae1bd60d54666d0a9dfa77fe7fe888879f5afa008411f2702b4e  
target: 000000003f833500000000000000000000000000000000000000000000000000
CBlock(hash=000000001e00ae1bd60d54666d0a9dfa77fe7fe888879f5afa008411f2702b4e, ver=7, hashPrevBlock=000000000cc74d7985343c471fe7448ee10b62ee6f6dfa28658f1c5d7541a93b, hashMerkleRoot=a0623537d673ca3b009b03b7a49deb219d2fc762830ab186f4229562379e923c, nTime=1615348401, nBits=1c3f8335, nNonce=1954437888, vtx=1, vchBlockSig=)
  Coinbase(hash=a0623537d673ca3b009b03b7a49deb219d2fc762830ab186f4229562379e923c, nTime=1615348381, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 03249d0e0103)
    CTxOut(nValue=5000.00, scriptPubKey=OP_DUP OP_HASH160 6a0c70663f2117481dfeda44bed7288afc500217 OP_EQUALVERIFY OP_CHECKSIG)

  vMerkleTree:  a0623537d673ca3b009b03b7a49deb219d2fc762830ab186f4229562379e923c

generated 5000.00
keypool keep 3
Checking for Velocity on block 957732: Velocity is currently Enabled
DENIED: Minimum block spacing not met for Velocity
ERROR: AcceptBlock() : Velocity rejected block 957732, required parameters not met
ERROR: ProcessBlock() : AcceptBlock FAILED
ERROR: CheckWork() : ProcessBlock, block not accepted
Terminal-Velocity retarget selected 
Espers retargetted using: Terminal-Velocity difficulty curve 
Previously discovered PoS block: 1615347856: 
Current block-time: 1615348128: 
Time since last PoS block: 272: 
Terminal-Velocity 1st spacing: 217: 
Terminal-Velocity 2nd spacing: 272: 
Terminal-Velocity 3rd spacing: 304: 
Terminal-Velocity 4th spacing: 624: 
Terminal-Velocity 5th spacing: 400: 
Desired normal spacing: 300: 
Desired maximum spacing: 450: 
Terminal-Velocity 1st multiplier set to: 2.000000: 
Terminal-Velocity 2nd multiplier set to: 1.250000: 
Terminal-Velocity 3rd multiplier set to: 1.000000: 
Terminal-Velocity 4th multiplier set to: 0.750000: 
Terminal-Velocity 5th multiplier set to: 1.000000: 
Terminal-Velocity averaged a final multiplier of: 1.200000: "

Followed: https://blog.espers.io/espers-mining-guide-522e46a6717d
Software: ccminer-2.0-release-x64-cuda-8.0
Mode: SOLO
Already rejected 4 blocks

**Comment by CryptoCoderz** [comment]
Mining works just fine bud, if you read the debug log you will where it rejected the block because it was created too soon after a previous block was accepted into the chain, this is a standard operation. 

If you leave your miner running when you find a block and all parameters are met (including it being long enough since the previous block was found) it will accept a block.

DENIED: Minimum block spacing not met for Velocity
ERROR: AcceptBlock() : Velocity rejected block 957732, required parameters not met

**Comment by tatdig** [comment]
So your software is rejecting idea of luck. To me it seams unfair. Quitting altogether. Glad it happened in the beginning.

**Comment by CryptoCoderz** [comment]
That's not what it's doing, It's preventing a sudden jump in hash from being able to affect the chain in a negative manner. It's anyone's game who gets a block, but the chain rate limits this to prevent bad actors from affecting the chain. 

This system has prevented a 51% attack several times. Take care but it's too bad you make assumptions instead of reading into the features and functionality of a blockchain

**Comment by tatdig** [comment]
Well, you have PoS blocks anyway right? I've spent hash power, found block, but have been rejected like I did something wrong. It would be nice if page mentioned above would explain your view, so who is not on the same page won't waste their time. I am not upset, just not sharing your view. 51% attack really :) somebody was able to spend input twice?

**Comment by CryptoCoderz** [comment]
I will make some documentation that is more forefront and I'll change how the system rejects the block to make it not appear to be an error as I can now see the confusion. 

No one was able to spend an input twice on our system, I was stating that this has prevented such a thing from happening in the past.

**Comment by tatdig** [comment]
On the miner side it is still going to be "Booo!" or you have to program your own miner IMO.
"51% attack really :) somebody was able to spend input twice?" I mean is somebody really attempted? How did you recognize such an attempt? Do you have checkpoints in place? ...

**Comment by CryptoCoderz** [comment]
We have an entire system in place to prevent such exploits among others such as timewarp and even selfishmining attacks.

It's called Velocity, it works in conjunction with the difficulty retarget system to notice key changes in hash patterns and to react to them. Normally you would not have received "Boo" as normally the difficulty is high enough that more hash isn't something that would cause you to make a block so fast that it would get rejected. 

But that being said you may have a lot of power in your rig(s) and the PoW hash could be very low so when you were mining you hit blocks like crazy but too soon since the previous block. 

Some other coins have the Velocity system built in as and each is a customized implementation depending on the blockchain's needs, in this case you could literally wait until 3 minutes have passed to start your miner up since the minimum block spacing window is 3 minutes. As long as someone else doesn't hit a block before you after the 3 minute mark you will get accepted when you make one.

This system is a departure from standard coins that allow any block spacing to be acceptable and as such doesn't play nice with standard miners hence it was acting like something was wrong and treating you like you did something wrong when in face the system was operating as intended.

**Comment by tatdig** [comment]
Interesting that you said that "have a lot of power in your rig(s)". I did mine with just one GTX970 and it was pure luck(see my second comment). By doing this you push away beginners. IMO

**Comment by tatdig** [comment]
Please don't feel like I am trying to steer you from your point of view, just sharing how it felt like from different perspective.

**Comment by CryptoCoderz** [comment]
"Interesting that you said that "have a lot of power in your rig(s)". I did mine with just one GTX970 and it was pure luck(see my second comment). By doing this you push away beginners. IMO"

lol there must not be too much hash on the network then, doesn't surprise me, we lost our pool for a while and many people stopped mining. My apologies for the off putting mining experience but indeed if you leave your miner running over night you'll definitely notice accepted blocks when you come to it again. I understand this is not the ideal mining experience to people who have never had this happen before.



"Please don't feel like I am trying to steer you from your point of view, just sharing how it felt like from different perspective."

Not at all! I would not have considered it an issue like I had done at first if you didn't mention it so I will be looking at making this different with how a miner experiences this blockchain and how the system react to a miner to make it more friendly and informative
