### ISSUE TITLE
RPC URL & MetaMask Wallet

### ISSUE THREAD

**Issue by cryptonred** [CryptoCoderz/Espers#56]
Does Espers have an RPC URL? I am currently trying to add Espers as a network to Metamask, an rpc url is required..

Alternatively, it would make sense to include Espers network in https://chainlist.org/, so you can add it to any web wallet with one click

**Comment by CryptoCoderz** [comment]
Espers is an independent blockchain, in other words it does not rely on ETH or other systems to operate.
Espers is NOT compatible with Metamask as Espers is its own blockchain and coin, NOT part of the ETH ecosystem.

Instead of using ETH or others that have centralized token control Espers and associated projects have banded together as integrated Altcoins to provide a more robust system with issues of ETH and others solved from the design itself.

If you'd like to use a web wallet we have a few available as anyone who interacts with Bitcoin can interact with our code (we have similar RPC calls)

You could think of us as the Polygon of the Altcoin world.
