### ISSUE TITLE
Compile issue on OpenSSL1.1.x version

### ISSUE THREAD

**Issue by Dafmulder** [CryptoCoderz/Espers#9]
Using a standard debian 9+ OpenSSL 1.1.x is the default package which breaks the compile process. 

Due to this [update](https://github.com/bitcoin/bitcoin/commit/b58be132c994b6f9b25cb4a702186ef96104953f)  the Bignum variables are not directly accessible anymore and cause errors.

**Comment by jaredabel** [comment]
Looking at other wallet issues, the way to fix it is to add some variation of

OPENSSL_INCLUDE_PATH=/usr/lib/Openssl-1.0/include/
OPENSSL_LIB_PATH=/usr/lib/Openssl-1.0/lib/

into the makefile.unix

although I am not knowledgeable enough to figure out exactly where and how i need to edit the makefile

**Comment by fu-raz** [comment]
On debian you can use
`apt -y install libssl1.0-dev`
To install an older version. Now you can compile it again.

**Comment by CryptoCoderz** [comment]
Though seamless cross platform usability is a high priority for the Espers project if an older openssl version is available for your OS, as fu-raz has pointed out, please utilize it in order to complete your build process.
Thank you jaredabel as well, just as a side note we do plan update openssl dependencies to 1.1 but at this time current version of Openssl 1.0.2 are still be in released and worked on, as such there are more pressing tasks to accomplish first and although it would be ideal to run on 1.1 it is currently still on the to do list.

Thank you two again for commenting, we will now lock this issue.

**Comment by CryptoCoderz** [comment]
Espers update/merge #30 has now resolved this issue. Closing.
